apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q3nat5n6j-java-springboot
  janus-idp.io/tekton: q3nat5n6j-java-springboot
  backstage.io/kubernetes-id: q3nat5n6j-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q3nat5n6j-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
